### ISSUE TITLE
User authentication token validation

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-gtk-usr#6]
We have two possibilities here (sorry, @luishens01, I do not remember our agreement on this):

1. the GK parses the token, checks the date validity of the token, checks the authorized endpoints and the endpoint that's being accessed... and replies !ok or forwards the request to the compoenent that will answer the request;
1. the GK forwards the token to the User Management, together with the endpoint that's being accessed, which replies ok or !ok... and the GK replies !ok or forwards the request to the compoenent that will answer the request;

Which one should we choose?

**Comment by luishens01** [comment]
Done. Authentication is working now.

**Comment by luishens01** [comment]
Authentication is working now.

**Comment by luishens01** [comment]
Authentication is working now.
